FROM node:14

ENV PORT 3000

# Create app directory
RUN mkdir -p /srv/app
WORKDIR /srv/app

# Installing dependencies
COPY package.json /srv/app
RUN yarn config set ignore-engines true
RUN yarn

# Copying source files
COPY . /srv/app

# Building app
# RUN npm run build
EXPOSE 3000
RUN npm run build
# Running the app
CMD "npm" "run" "start"